environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^1.7.0
  intl: ^0.15.8
  sy_flutter_widgets: ^0.1.4
  flutter_chips_input: ^1.5.1
  datetime_picker_formfield: ^1.0.0-pre.5
  # signature: ^2.0.0 - Doesn't implement onChanged, submitted PR. Meanwhile using local clone with onChanged
  validators: ^2.0.0+1
  date_range_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3

flutter:
